# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-28 09:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pools', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='credit',
            field=models.CharField(default=100, max_length=20),
            preserve_default=False,
        ),
    ]
