# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-06 04:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pools', '0002_customer_credit'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
