# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-06 10:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pools', '0003_product_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deliver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addTime', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(max_length=20)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pools.Order')),
            ],
        ),
        migrations.CreateModel(
            name='DeliverDatail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deliverNum', models.IntegerField()),
                ('deliver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pools.Deliver')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pools.Product')),
            ],
        ),
    ]
