# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-03 12:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pools', '0004_deliver_deliverdatail'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employName', models.CharField(max_length=30)),
                ('employDepart', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='ProducttoSupplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField()),
            ],
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='user',
        ),
        migrations.RemoveField(
            model_name='purchasedatail',
            name='product',
        ),
        migrations.RemoveField(
            model_name='purchasedatail',
            name='purchase',
        ),
        migrations.RemoveField(
            model_name='stocknotice',
            name='order',
        ),
        migrations.RemoveField(
            model_name='stocknotice',
            name='user',
        ),
        migrations.RemoveField(
            model_name='stocknoticedetail',
            name='product',
        ),
        migrations.RemoveField(
            model_name='stocknoticedetail',
            name='stocknotice',
        ),
        migrations.RemoveField(
            model_name='order',
            name='outDemandTimes',
        ),
        migrations.RemoveField(
            model_name='payable',
            name='purchase',
        ),
        migrations.RemoveField(
            model_name='product',
            name='purchasePrice',
        ),
        migrations.RemoveField(
            model_name='product',
            name='status',
        ),
        migrations.RemoveField(
            model_name='product',
            name='supplier',
        ),
        migrations.RemoveField(
            model_name='receivable',
            name='stocknotice',
        ),
        migrations.RemoveField(
            model_name='user',
            name='realName',
        ),
        migrations.RemoveField(
            model_name='user',
            name='userDepart',
        ),
        migrations.AddField(
            model_name='againpurchase',
            name='supplier',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pools.Supplier'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pools.User'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='deliver',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pools.User'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='sumprice',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payable',
            name='againpurchase',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pools.Againpurchase'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='receivable',
            name='Deliver',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pools.Deliver'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='supplier',
            name='credit',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='supplier',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pools.User'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Purchase',
        ),
        migrations.DeleteModel(
            name='PurchaseDatail',
        ),
        migrations.DeleteModel(
            name='Stocknotice',
        ),
        migrations.DeleteModel(
            name='StocknoticeDetail',
        ),
        migrations.AddField(
            model_name='producttosupplier',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pools.Product'),
        ),
        migrations.AddField(
            model_name='producttosupplier',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pools.Supplier'),
        ),
        migrations.AddField(
            model_name='employee',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pools.User'),
        ),
    ]
